version: '3.8'
services:
  vet-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vet-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev